"""Add checked fields

Revision ID: 153f3ea8a9ab
Revises: e3604ab010df
Create Date: 2025-04-16 09:32:04.719887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153f3ea8a9ab'
down_revision = 'e3604ab010df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('checked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'checked')
    # ### end Alembic commands ###
