"""Fixed Permit table schema

Revision ID: 37e4513f5f30
Revises: d65f4c59af7c
Create Date: 2025-02-05 09:17:36.303127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37e4513f5f30'
down_revision = 'd65f4c59af7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit',
    sa.Column('salutation', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('number_of_animals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('animal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cattle_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('other_animal_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('origin_district', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('destination_district', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('movement_period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('route', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('payment_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_amount_in_words', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Submitted'::character varying"), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('origin_status', sa.VARCHAR(length=20), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('destination_status', sa.VARCHAR(length=20), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permit_pkey')
    )
    # ### end Alembic commands ###
