"""Recreate migration to drop audit_logs and permit tables safely

Revision ID: d65f4c59af7c
Revises: 
Create Date: 2025-01-29 10:16:02.819788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd65f4c59af7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mutare_submission')
    op.drop_table('audit_logs')
    op.drop_table('permit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit',
    sa.Column('salutation', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('number_of_animals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('animal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cattle_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('other_animal_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('origin_district', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('destination_district', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('movement_period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('route', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('payment_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_amount_in_words', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Submitted'::character varying"), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('origin_status', sa.VARCHAR(length=20), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('destination_status', sa.VARCHAR(length=20), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permit_pkey')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('permit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_table('mutare_submission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mutare_submission_pkey')
    )
    # ### end Alembic commands ###
